/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PayablesRouteImport } from './routes/payables'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PurchasePointRouteImport } from './routes/purchase-point'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReceivablesRouteImport } from './routes/receivables'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PayablesRoute = PayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasePointRoute = PurchasePointRouteImport.update({
  id: '/purchase-point',
  path: '/purchase-point',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivablesRoute = ReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/payables': typeof PayablesRoute
  '/pos': typeof PosRoute
  '/purchase-point': typeof PurchasePointRoute
  '/purchases': typeof PurchasesRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/payables': typeof PayablesRoute
  '/pos': typeof PosRoute
  '/purchase-point': typeof PurchasePointRoute
  '/purchases': typeof PurchasesRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/payables': typeof PayablesRoute
  '/pos': typeof PosRoute
  '/purchase-point': typeof PurchasePointRoute
  '/purchases': typeof PurchasesRoute
  '/receivables': typeof ReceivablesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/inventory'
    | '/payables'
    | '/pos'
    | '/purchase-point'
    | '/purchases'
    | '/receivables'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/inventory'
    | '/payables'
    | '/pos'
    | '/purchase-point'
    | '/purchases'
    | '/receivables'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/inventory'
    | '/payables'
    | '/pos'
    | '/purchase-point'
    | '/purchases'
    | '/receivables'
    | '/reports'
    | '/sales'
    | '/suppliers'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  InventoryRoute: typeof InventoryRoute
  PayablesRoute: typeof PayablesRoute
  PosRoute: typeof PosRoute
  PurchasePointRoute: typeof PurchasePointRoute
  PurchasesRoute: typeof PurchasesRoute
  ReceivablesRoute: typeof ReceivablesRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SuppliersRoute: typeof SuppliersRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payables': {
      id: '/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof PayablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-point': {
      id: '/purchase-point'
      path: '/purchase-point'
      fullPath: '/purchase-point'
      preLoaderRoute: typeof PurchasePointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivables': {
      id: '/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof ReceivablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  InventoryRoute: InventoryRoute,
  PayablesRoute: PayablesRoute,
  PosRoute: PosRoute,
  PurchasePointRoute: PurchasePointRoute,
  PurchasesRoute: PurchasesRoute,
  ReceivablesRoute: ReceivablesRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SuppliersRoute: SuppliersRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
